// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbenlgxinwkdgwqibjwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZW5sZ3hpbndrZGd3cWliandoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODc1MDgsImV4cCI6MjA3Mzg2MzUwOH0.qTkUFsJt0zkhC8dNS0DiKchn-g2BS9YMJB9FFIaeU4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});